/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus metrics */
        get: operations["metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partners/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список заявок (scope-фильтр, курсорная пагинация)
         * @description Видимые субъекту заявки (контур access_level + владение). Курсорная пагинация; фильтры status / category / partner_id / период (§11.1).
         */
        get: operations["listRequests"];
        put?: never;
        /**
         * Приём заявки (ЛК-форма / m2m)
         * @description FR-1.1/FR-1.4. `channel_in` выводится бэкендом из типа субъекта (не из тела). Идемпотентность — по заголовку `Idempotency-Key`.
         */
        post: operations["createRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partners/requests/from-chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Приём заявки из AI-чата (kb-search, SERVICE-only)
         * @description FR-1.2. Только сервис-принципал (m2m). Идемпотентность по `chat_session_id`.
         */
        post: operations["createRequestFromChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partners/requests/from-ticket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Эскалация заявки из тикета (kb-support, SERVICE-only)
         * @description FR-1.3. Только сервис-принципал (m2m). Идемпотентность по `ticket_id`.
         */
        post: operations["createRequestFromTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partners/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        /**
         * Карточка заявки + allowed_transitions
         * @description Карточка с `allowed_transitions` (§7). `raw_input` маскируется по scope. Недоступный ресурс → 404 (анти-enumeration).
         */
        get: operations["getRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partners/requests/{request_id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Переход статуса (валидация по FSM)
         * @description Переход FSM (§7). Запрещённый → 409; недоступная → 404; нет прав → 403.
         */
        post: operations["transitionRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partners/requests/{request_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Отмена заявки (с причиной)
         * @description Отмена из нетерминального статуса (§7). Партнёру запрещена (403).
         */
        post: operations["cancelRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partners/requests/{request_id}/classify": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * (Ре)классификация категории (operator/agent)
         * @description E2: rules + LLM по `raw_input_masked` (FR-2.1–2.3); ниже порога уверенности или неоднозначно → NEEDS_REVIEW (FR-2.4). Трассировка в `classification`.
         */
        post: operations["classifyRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partners/requests/{request_id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Подбор / назначение партнёра (operator/agent)
         * @description E3 (FR-3.1–3.4). partner_id → ручное назначение; пусто → авто-подбор по реестру kb-platform (ранжирование + fallback_chain + match_trace).
         */
        post: operations["assignRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partners/requests/{request_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Приёмка пользователем
         * @description FR-7.1. DONE→ACCEPTED_BY_USER. Партнёру недоступно (403); не DONE → 409.
         */
        post: operations["acceptRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partners/requests/{request_id}/dispute": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Открыть спор (с причиной)
         * @description FR-7.2. DONE|ACCEPTED_BY_USER→DISPUTE; при сконфигурированном контуре порождает претензию COMPENSATION в kb-support (claim_ref).
         */
        post: operations["disputeRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partners/requests/{request_id}/settlement": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Подтверждение расчёта контуром (SERVICE-only)
         * @description FR-7.3. Платёжный контур rehome.one подтверждает расчёт → ACCEPTED_BY_USER→PAID. Деньги модуль не считает — хранит ссылки.
         */
        post: operations["confirmSettlement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partners/requests/{request_id}/dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Диспетчеризация партнёру (operator/agent)
         * @description E4 (FR-4.1–4.6). Доставка по каналу с наивысшим priority среди активных; fallback по партнёрам цепочки; исчерпание → FAILED_DISPATCH. Каждая попытка — DispatchAttempt.
         */
        post: operations["dispatchRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partners/requests/{request_id}/partner-response": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ответ партнёра (портал LIGHT)
         * @description E10/FR-10.2. Партнёр accepted/rejected/in_progress/done по своей заявке. Только партнёр (403); чужая → 404; запрещённый переход → 409; неизвестный → 422.
         */
        post: operations["partnerResponse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partners/requests/{request_id}/requester-context": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        /**
         * Контекст заявителя из rehome.one (operator/agent)
         * @description E9/FR-9.1. User/Premises/Booking заявителя (контекст для оператора/агента). Только привилегированные роли (403); недоступная заявка → 404.
         */
        get: operations["getRequesterContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partners/requests/{request_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        /**
         * Сообщения заявки (внутренние — только операторам)
         * @description Хронология; `is_internal`-заметки скрыты от заявителя/партнёра (правило 10).
         */
        get: operations["listRequestMessages"];
        put?: never;
        /**
         * Сообщение / внутренняя заметка
         * @description Добавить сообщение. `is_internal=true` — только оператор (иначе 403). Недоступная заявка → 404.
         */
        post: operations["addRequestMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partners/inbound/api/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Входящее от партнёра (подписанный webhook) */
        post: operations["inboundApi"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partners/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список конфигураций каналов */
        get: operations["listChannels"];
        put?: never;
        /** Создать конфигурацию канала */
        post: operations["createChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/partners/channels/{config_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        /** Карточка конфигурации канала */
        get: operations["getChannel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Изменить конфигурацию канала */
        patch: operations["updateChannel"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Healthz: {
            /** @enum {string} */
            status: "ok";
        };
        /** @description RFC 7807 problem+json (без ПДн в detail). */
        Error: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string;
            errors?: {
                [key: string]: string;
            }[];
        };
        /** @enum {string} */
        ChannelIn: "WEB_FORM" | "AI_CHAT" | "SUPPORT_TICKET" | "API" | "MESSENGER_INBOUND";
        /** @enum {string} */
        Category: "CLEANING" | "MOVING" | "REPAIR" | "KEY_DELIVERY" | "OTHER";
        /** @enum {string} */
        RequestStatus: "NEW" | "CLASSIFYING" | "CLASSIFIED" | "NEEDS_REVIEW" | "MATCHING" | "ASSIGNED" | "DISPATCHED" | "FAILED_DISPATCH" | "ACCEPTED" | "IN_PROGRESS" | "DONE" | "ACCEPTED_BY_USER" | "DISPUTE" | "PAID" | "CANCELLED" | "REJECTED";
        /** @description Тело приёма из ЛК-формы / m2m. `channel_in` НЕ принимается (выводится бэкендом); `raw_input` маскируется до логов/LLM (FR-1.6). */
        RequestCreate: {
            raw_input: string;
            requester_id?: string;
            booking_id?: string;
            premises_id?: string;
            source_ref?: {
                [key: string]: unknown;
            };
        };
        /** @description Тело инициации из AI-чата (kb-search). Идемпотентность по chat_session_id. */
        FromChatCreate: {
            chat_session_id: string;
            requester_id: string;
            raw_input: string;
            transcript?: {
                [key: string]: unknown;
            }[];
            booking_id?: string;
            premises_id?: string;
        };
        /** @description Тело эскалации из тикета (kb-support). Идемпотентность по ticket_id. */
        FromTicketCreate: {
            ticket_id: string;
            requester_id: string;
            raw_input: string;
            booking_id?: string;
            premises_id?: string;
        };
        /** @description Представление заявки наружу. Без raw_input (ПДн, FR-1.6/NFR-5). */
        RequestRead: {
            /** Format: uuid */
            id: string;
            number: string;
            requester_id: string;
            channel_in: components["schemas"]["ChannelIn"];
            category: components["schemas"]["Category"] | null;
            status: components["schemas"]["RequestStatus"];
            /** Format: date-time */
            created_at: string;
        };
        /** @enum {string} */
        AuthorType: "REQUESTER" | "OPERATOR" | "PARTNER" | "SYSTEM" | "AI";
        /** @description Карточка заявки: поля RequestRead + allowed_transitions (§7) и scope-маскированный raw_input (оператор/владелец — исходник, партнёр — маска). */
        RequestDetail: {
            /** Format: uuid */
            id: string;
            number: string;
            requester_id: string;
            channel_in: components["schemas"]["ChannelIn"];
            category: components["schemas"]["Category"] | null;
            status: components["schemas"]["RequestStatus"];
            /** Format: date-time */
            created_at: string;
            partner_id: string | null;
            product_code: string | null;
            booking_id: string | null;
            premises_id: string | null;
            delivery_channel: string | null;
            service_order_id: string | null;
            amount_ref: string | null;
            escrow_ref: string | null;
            dispute_id: string | null;
            claim_ref: string | null;
            /** Format: date-time */
            updated_at: string;
            raw_input: string;
            classification: {
                [key: string]: unknown;
            } | null;
            /** @description SLA-дедлайны + вычисленные на чтении состояния (E6). */
            sla: {
                [key: string]: unknown;
            } | null;
            /** @description Объяснимость подбора (только сотрудникам; иначе null). */
            match_trace: {
                [key: string]: unknown;
            } | null;
            /** @description Упорядоченные collaborator_id для авто-fallback (только сотрудникам). */
            fallback_chain: string[] | null;
            allowed_transitions: components["schemas"]["RequestStatus"][];
        };
        /** @description partner_id задан → ручное назначение (FR-3.4); пусто → авто-подбор по реестру (service_area — опциональный гео-фильтр). */
        AssignRequest: {
            partner_id?: string;
            service_area?: string;
        };
        /** @description Ссылка на вложение в kb-files (FR-1.5). */
        AttachmentRef: {
            file_id: string;
            filename?: string | null;
            content_type?: string | null;
        };
        /** @description Сообщение/заметка. is_internal=true — только оператор (иначе 403). */
        MessageCreate: {
            text: string;
            /** @default false */
            is_internal: boolean;
            attachments?: components["schemas"]["AttachmentRef"][];
        };
        /** @description Сообщение заявки. Внутренние заметки в выдаче — только операторам. */
        MessageRead: {
            /** Format: uuid */
            id: string;
            author_type: components["schemas"]["AuthorType"];
            author_id: string | null;
            is_internal: boolean;
            text: string;
            attachments: {
                [key: string]: unknown;
            }[];
            /** Format: date-time */
            created_at: string;
        };
        /** @description Переход FSM; target валидируется по §7. */
        TransitionRequest: {
            target: components["schemas"]["RequestStatus"];
        };
        /** @description Отмена заявки с обязательной причиной. */
        CancelRequest: {
            reason: string;
        };
        /** @description Открытие спора с обязательной причиной (FR-7.2). */
        DisputeRequest: {
            reason: string;
        };
        /** @description Подтверждение расчёта платёжным контуром (FR-7.3). Только ссылки. */
        SettlementConfirm: {
            amount_ref?: string;
            escrow_ref?: string;
        };
        /** @description Ответ партнёра по заявке (E10, FR-10.2). */
        PartnerResponse: {
            /** @description accepted / rejected / in_progress / done. */
            status: string;
            message?: string;
        };
        /** @description Контекст заявителя из rehome.one (E9). Все поля опциональны. */
        RequesterContextResponse: {
            user_display_name?: string | null;
            user_phone?: string | null;
            user_email?: string | null;
            premises_address?: string | null;
            booking_status?: string | null;
        };
        /** @description Страница списка заявок + курсор следующей страницы (или null). */
        RequestListResponse: {
            items: components["schemas"]["RequestRead"][];
            next_cursor: string | null;
        };
        /** @enum {string} */
        ChannelType: "API" | "CRM" | "TELEGRAM" | "MAX" | "EMAIL" | "MOCK";
        /** @description Конверт входящего от партнёра (E5). Подпись/таймстемп — в заголовках. */
        InboundEnvelope: {
            request_ref: string;
            /** @description accepted / rejected / in_progress / done. */
            status: string;
            nonce: string;
            message?: string;
        };
        /** @description Конфигурация канала партнёра. inbound_token — секрет, в выдаче не возвращается. */
        ChannelConfigCreate: {
            collaborator_id: string;
            channel_type: components["schemas"]["ChannelType"];
            /** @default 100 */
            priority: number;
            config?: {
                [key: string]: unknown;
            };
            inbound_token?: string;
            /** @default true */
            is_active: boolean;
        };
        /** @description Частичное обновление канала. */
        ChannelConfigUpdate: {
            priority?: number;
            config?: {
                [key: string]: unknown;
            };
            inbound_token?: string;
            is_active?: boolean;
        };
        /** @description Представление канала. БЕЗ inbound_token (секрет). */
        ChannelConfigRead: {
            /** Format: uuid */
            id: string;
            collaborator_id: string;
            channel_type: components["schemas"]["ChannelType"];
            priority: number;
            config: {
                [key: string]: unknown;
            };
            is_active: boolean;
            health: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Процесс жив. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Healthz"];
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Готов к трафику (БД доступна; redis — мягкий статус). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Не готов (БД недоступна). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Метрики в формате Prometheus exposition. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    listRequests: {
        parameters: {
            query?: {
                status?: components["schemas"]["RequestStatus"];
                category?: components["schemas"]["Category"];
                partner_id?: string;
                created_from?: string;
                created_to?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница заявок. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestListResponse"];
                };
            };
            /** @description Не аутентифицирован. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    createRequest: {
        parameters: {
            query?: never;
            header?: {
                /** @description Ключ дедупликации приёма; повтор возвращает существующую заявку (200). */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCreate"];
            };
        };
        responses: {
            /** @description Идемпотентный повтор — существующая заявка. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRead"];
                };
            };
            /** @description Заявка создана. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRead"];
                };
            };
            /** @description Не аутентифицирован. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Ошибка валидации тела. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    createRequestFromChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FromChatCreate"];
            };
        };
        responses: {
            /** @description Идемпотентный повтор — существующая заявка. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRead"];
                };
            };
            /** @description Заявка создана. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRead"];
                };
            };
            /** @description Требуется сервис-принципал. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    createRequestFromTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FromTicketCreate"];
            };
        };
        responses: {
            /** @description Идемпотентный повтор — существующая заявка. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRead"];
                };
            };
            /** @description Заявка создана. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRead"];
                };
            };
            /** @description Требуется сервис-принципал. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    getRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Карточка заявки. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestDetail"];
                };
            };
            /** @description Заявка не найдена или недоступна. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    transitionRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionRequest"];
            };
        };
        responses: {
            /** @description Новое состояние карточки. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestDetail"];
                };
            };
            /** @description Действие недоступно субъекту. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Заявка не найдена или недоступна. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Запрещённый переход (FSM). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    cancelRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelRequest"];
            };
        };
        responses: {
            /** @description Заявка отменена. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestDetail"];
                };
            };
            /** @description Действие недоступно субъекту. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Заявка не найдена или недоступна. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Заявка уже в терминальном статусе. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    classifyRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Карточка с обновлённой категорией/классификацией. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestDetail"];
                };
            };
            /** @description Доступно только оператору/агенту. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Заявка не найдена или недоступна. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Классификация недопустима в текущем статусе. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    assignRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRequest"];
            };
        };
        responses: {
            /** @description Назначено; карточка с partner_id/каналом/трассировкой. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestDetail"];
                };
            };
            /** @description Действие недоступно субъекту. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Заявка не найдена или недоступна. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Назначение недопустимо в текущем статусе / заявка не классифицирована. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Нет пригодных партнёров для авто-подбора. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    acceptRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Заявка принята пользователем. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestDetail"];
                };
            };
            /** @description Действие недоступно субъекту. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Заявка не найдена или недоступна. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Приёмка недопустима в текущем статусе. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    disputeRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisputeRequest"];
            };
        };
        responses: {
            /** @description Спор открыт. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestDetail"];
                };
            };
            /** @description Действие недоступно субъекту. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Заявка не найдена или недоступна. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Спор недопустим в текущем статусе. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    confirmSettlement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettlementConfirm"];
            };
        };
        responses: {
            /** @description Заявка оплачена (PAID). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestDetail"];
                };
            };
            /** @description Требуется сервис-принципал. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Заявка не найдена. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Расчёт недопустим в текущем статусе. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    dispatchRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Результат диспетчеризации (DISPATCHED или FAILED_DISPATCH). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestDetail"];
                };
            };
            /** @description Действие недоступно субъекту. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Заявка не найдена или недоступна. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Диспетчеризация недопустима в текущем статусе. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    partnerResponse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartnerResponse"];
            };
        };
        responses: {
            /** @description Новое состояние карточки. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestDetail"];
                };
            };
            /** @description Доступно только партнёру-исполнителю. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Заявка не найдена или недоступна. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Запрещённый переход (FSM). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Неизвестный статус партнёра. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    getRequesterContext: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Контекст заявителя (поля опциональны / контур недоступен → null). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequesterContextResponse"];
                };
            };
            /** @description Доступно только оператору/агенту. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Заявка не найдена или недоступна. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    listRequestMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список сообщений. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageRead"][];
                };
            };
            /** @description Заявка не найдена или недоступна. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    addRequestMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description Сообщение добавлено. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageRead"];
                };
            };
            /** @description Внутренняя заметка доступна только оператору. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Заявка не найдена или недоступна. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    inboundApi: {
        parameters: {
            query?: never;
            header: {
                /** @description HMAC-SHA256(`<X-Timestamp>.<body>`, inbound_token), hex. */
                "X-Signature": string;
                /** @description Epoch-секунды; вне окна ±300с → 401 (replay-защита). */
                "X-Timestamp": string;
            };
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InboundEnvelope"];
            };
        };
        responses: {
            /** @description Принято (`ok`) либо дубль (`duplicate`). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status?: "ok" | "duplicate";
                    };
                };
            };
            /** @description Невалидная подпись или таймстемп. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Неизвестный токен либо заявка вне ведения партнёра. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Некорректное тело или неизвестный статус. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    listChannels: {
        parameters: {
            query?: {
                collaborator_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список каналов. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelConfigRead"][];
                };
            };
            /** @description Требуется admin-скоуп. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    createChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelConfigCreate"];
            };
        };
        responses: {
            /** @description Канал создан. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelConfigRead"];
                };
            };
            /** @description Требуется admin-скоуп. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
            /** @description Канал для этого партнёра и типа уже существует. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    getChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Конфигурация канала. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelConfigRead"];
                };
            };
            /** @description Не найдено. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                config_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelConfigUpdate"];
            };
        };
        responses: {
            /** @description Обновлённая конфигурация. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelConfigRead"];
                };
            };
            /** @description Не найдено. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Error"];
                };
            };
        };
    };
}
